### ISSUE TITLE
Make filter parsing case insensitive

### ISSUE THREAD

**Issue by thomasbalstroem** [Septima/malstroem#39]
Apparently, in Malstroem ver. 270924, the AND operator is not accepted for the Filter option. Example: -filter "volume > 1 AND maxdepth > 0.1". 
The error message says:

Traceback (most recent call last):
  File "malstroem\scripts\cli.py", line 89, in <module>
  File "click\core.py", line 1157, in __call__
  File "click\core.py", line 1078, in main
  File "click\core.py", line 1688, in invoke
  File "click\core.py", line 1434, in invoke
  File "click\core.py", line 783, in invoke
  File "malstroem\scripts\complete.py", line 58, in process_all
  File "malstroem\scripts\_utils.py", line 33, in parse_filter
  File "malstroem\scripts\_utils.py", line 26, in check_filter
Exception: Unsupported filter statement. Illegal parts: AND
[PYI-16520:ERROR] Failed to execute script 'cli' due to unhandled exception!

Kind regards, Thomas Balstrøm, Univ. of Copenhagen

**Comment by AsgerPetersen** [comment]
Hi @thomasbalstroem 

Could you please try using lower case 'and' instead of upper case?

Best regards
